part of 'remote_storage_config.dart';

// Keeps immutable configuration updates separate from JSON parsing and defaults.
extension RemoteStorageConfigCopy on RemoteStorageConfig {
  RemoteStorageConfig copyWith({
    String? endpoint,
    StorageType? storageType,
    StorageProviderType? providerType,
    String? displayName,
    String? profileId,
    String? mappedBucketName,
    String? region,
    String? bucket,
    String? accessKeyId,
    String? secretAccessKey,
    bool? hasSecretAccessKey,
    String? webdavUsername,
    String? webdavPassword,
    bool? hasWebdavPassword,
    String? ftpUsername,
    String? ftpPassword,
    bool? hasFtpPassword,
    int? ftpPort,
    bool? ftpAnonymous,
    String? rootPrefix,
    String? defaultDownloadDirectory,
    String? cacheDirectory,
    String? resolvedCacheDirectory,
    bool? hideDotFiles,
    FileOpenMode? fileOpenMode,
    String? trashDirectoryName,
    int? trashRetentionDays,
    Map<String, BucketSettings>? bucketSettings,
    Map<String, BucketViewSettings>? bucketViews,
    int? writebackQuietSeconds,
    int? mountMetadataCacheSeconds,
    int? mountRemotePollSeconds,
    bool? usePathStyle,
    WindowsMountMode? windowsMountMode,
    WindowsMountEngine? windowsMountEngine,
    int? windowsWinFspCapacityGb,
    bool? windowsThisPcEntryEnabled,
    int? windowsWritebackConcurrency,
    bool? cacheAutoCleanupEnabled,
    int? cacheMaxSizeMb,
    int? cacheMaxAgeDays,
    JWanFSGatewayMode? jwanfsGatewayMode,
    String? proxyMode,
    String? proxyType,
    String? proxyHost,
    String? proxyPort,
    String? proxyUsername,
    String? proxyPassword,
    bool? p2pEnabled,
    int? p2pChunkSizeMb,
    bool? disabled,
  }) {
    return RemoteStorageConfig(
      endpoint: endpoint ?? this.endpoint,
      storageType: storageType ?? this.storageType,
      providerType: providerType ?? this.providerType,
      displayName: displayName ?? this.displayName,
      profileId: profileId ?? this.profileId,
      mappedBucketName: mappedBucketName ?? this.mappedBucketName,
      region: region ?? this.region,
      bucket: bucket ?? this.bucket,
      accessKeyId: accessKeyId ?? this.accessKeyId,
      secretAccessKey: secretAccessKey ?? this.secretAccessKey,
      hasSecretAccessKey: hasSecretAccessKey ?? this.hasSecretAccessKey,
      webdavUsername: webdavUsername ?? this.webdavUsername,
      webdavPassword: webdavPassword ?? this.webdavPassword,
      hasWebdavPassword: hasWebdavPassword ?? this.hasWebdavPassword,
      ftpUsername: ftpUsername ?? this.ftpUsername,
      ftpPassword: ftpPassword ?? this.ftpPassword,
      hasFtpPassword: hasFtpPassword ?? this.hasFtpPassword,
      ftpPort: ftpPort ?? this.ftpPort,
      ftpAnonymous: ftpAnonymous ?? this.ftpAnonymous,
      rootPrefix: rootPrefix ?? this.rootPrefix,
      defaultDownloadDirectory:
          defaultDownloadDirectory ?? this.defaultDownloadDirectory,
      cacheDirectory: cacheDirectory ?? this.cacheDirectory,
      resolvedCacheDirectory:
          resolvedCacheDirectory ?? this.resolvedCacheDirectory,
      hideDotFiles: hideDotFiles ?? this.hideDotFiles,
      fileOpenMode: fileOpenMode ?? this.fileOpenMode,
      trashDirectoryName: trashDirectoryName ?? this.trashDirectoryName,
      trashRetentionDays: trashRetentionDays ?? this.trashRetentionDays,
      bucketSettings: bucketSettings ?? this.bucketSettings,
      bucketViews: bucketViews ?? this.bucketViews,
      writebackQuietSeconds:
          writebackQuietSeconds ?? this.writebackQuietSeconds,
      mountMetadataCacheSeconds:
          mountMetadataCacheSeconds ?? this.mountMetadataCacheSeconds,
      mountRemotePollSeconds:
          mountRemotePollSeconds ?? this.mountRemotePollSeconds,
      usePathStyle: usePathStyle ?? this.usePathStyle,
      windowsMountMode: windowsMountMode ?? this.windowsMountMode,
      windowsMountEngine: windowsMountEngine ?? this.windowsMountEngine,
      windowsWinFspCapacityGb:
          windowsWinFspCapacityGb ?? this.windowsWinFspCapacityGb,
      windowsThisPcEntryEnabled:
          windowsThisPcEntryEnabled ?? this.windowsThisPcEntryEnabled,
      windowsWritebackConcurrency:
          windowsWritebackConcurrency ?? this.windowsWritebackConcurrency,
      cacheAutoCleanupEnabled:
          cacheAutoCleanupEnabled ?? this.cacheAutoCleanupEnabled,
      cacheMaxSizeMb: cacheMaxSizeMb ?? this.cacheMaxSizeMb,
      cacheMaxAgeDays: cacheMaxAgeDays ?? this.cacheMaxAgeDays,
      jwanfsGatewayMode: jwanfsGatewayMode ?? this.jwanfsGatewayMode,
      proxyMode: proxyMode ?? this.proxyMode,
      proxyType: proxyType ?? this.proxyType,
      proxyHost: proxyHost ?? this.proxyHost,
      proxyPort: proxyPort ?? this.proxyPort,
      proxyUsername: proxyUsername ?? this.proxyUsername,
      proxyPassword: proxyPassword ?? this.proxyPassword,
      p2pEnabled: p2pEnabled ?? this.p2pEnabled,
      p2pChunkSizeMb: p2pChunkSizeMb ?? this.p2pChunkSizeMb,
      disabled: disabled ?? this.disabled,
    );
  }
}
